from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Dict, List


def parse_segments(job_dir: Path) -> List[Dict[str, str]]:
    """Extract timestamped text segments from transcript.json or transcript.srt."""
    json_path = job_dir / "transcript.json"
    segments: List[Dict[str, str]] = []

    if json_path.exists():
        try:
            data = json.loads(json_path.read_text(encoding="utf-8", errors="replace"))
            raw_transcription = data.get("transcription") or data.get("segments") or []
            for item in raw_transcription:
                if isinstance(item, dict):
                    ts = item.get("timestamps", {})
                    start = ts.get("from") if isinstance(ts, dict) else item.get("start", "")
                    end = ts.get("to") if isinstance(ts, dict) else item.get("end", "")
                    text = item.get("text", "").strip()
                    if text:
                        start_str = str(start).split(",")[0] if "," in str(start) else str(start)
                        segments.append({"start": str(start_str), "end": str(end), "text": text})
        except Exception:
            pass

    if not segments and (job_dir / "transcript.srt").exists():
        try:
            content = (job_dir / "transcript.srt").read_text(encoding="utf-8", errors="replace")
            blocks = content.strip().split("\n\n")
            for block in blocks:
                lines = block.strip().splitlines()
                if len(lines) >= 3 and "-->" in lines[1]:
                    time_part = lines[1].split("-->")[0].strip().split(",")[0]
                    text = " ".join(lines[2:]).strip()
                    if text:
                        segments.append({"start": time_part, "end": "", "text": text})
        except Exception:
            pass

    return segments


def generate_markdown(title: str, segments: List[Dict[str, str]], full_text: str) -> str:
    md = [f"# {title}\n", "*Generated by ULTRANSC*\n\n---\n"]
    if segments:
        md.append("## Timeline\n")
        for seg in segments:
            start = seg.get("start", "00:00:00")
            text = seg.get("text", "")
            md.append(f"- **[{start}]** {text}")
        md.append("\n---\n")
    md.append("## Full Transcript\n\n")
    md.append(full_text.strip() + "\n")
    return "\n".join(md)


def generate_html(title: str, segments: List[Dict[str, str]], full_text: str) -> str:
    escaped_title = html.escape(title)
    escaped_full_text = html.escape(full_text)

    segment_elements = []
    for seg in segments:
        start = html.escape(seg.get("start", "00:00:00"))
        text = html.escape(seg.get("text", ""))
        segment_elements.append(
            f'<div class="segment" data-text="{text.lower()}">'
            f'<span class="badge">{start}</span>'
            f'<span class="content">{text}</span>'
            f"</div>"
        )
    segments_html = "\n".join(segment_elements) or f"<p>{escaped_full_text}</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{escaped_title} - ULTRANSC Transcript</title>
  <style>
    :root {{
      --bg: #0f172a;
      --card-bg: #1e293b;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --primary: #38bdf8;
      --border: #334155;
      --badge-bg: #0369a1;
      --badge-text: #e0f2fe;
    }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 2rem 1rem;
      display: flex;
      justify-content: center;
    }}
    .container {{
      max-width: 800px;
      width: 100%;
    }}
    header {{
      margin-bottom: 2rem;
      border-bottom: 1px solid var(--border);
      padding-bottom: 1rem;
    }}
    h1 {{
      font-size: 1.75rem;
      margin: 0 0 0.5rem 0;
      color: var(--primary);
    }}
    .subtitle {{
      color: var(--text-muted);
      font-size: 0.9rem;
    }}
    .controls {{
      margin-bottom: 1.5rem;
      display: flex;
      gap: 1rem;
    }}
    .search-box {{
      flex: 1;
      padding: 0.75rem 1rem;
      border-radius: 0.5rem;
      border: 1px solid var(--border);
      background: var(--card-bg);
      color: var(--text);
      font-size: 1rem;
      outline: none;
    }}
    .search-box:focus {{
      border-color: var(--primary);
    }}
    .btn {{
      padding: 0.75rem 1.25rem;
      border-radius: 0.5rem;
      border: none;
      background: var(--primary);
      color: #0f172a;
      font-weight: 600;
      cursor: pointer;
      transition: opacity 0.2s;
    }}
    .btn:hover {{
      opacity: 0.9;
    }}
    .segments {{
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }}
    .segment {{
      background: var(--card-bg);
      padding: 1rem;
      border-radius: 0.5rem;
      border: 1px solid var(--border);
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      line-height: 1.6;
    }}
    .badge {{
      background: var(--badge-bg);
      color: var(--badge-text);
      padding: 0.2rem 0.5rem;
      border-radius: 0.25rem;
      font-size: 0.8rem;
      font-family: monospace;
      white-space: nowrap;
      user-select: none;
    }}
    .content {{
      flex: 1;
    }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>{escaped_title}</h1>
      <div class="subtitle">Generated by ULTRANSC Transcription Pipeline</div>
    </header>

    <div class="controls">
      <input type="text" id="search" class="search-box" placeholder="Search transcript..." />
      <button class="btn" onclick="copyTranscript()">Copy All</button>
    </div>

    <div class="segments" id="segmentsList">
      {segments_html}
    </div>
  </div>

  <script>
    const searchInput = document.getElementById('search');
    const segments = document.querySelectorAll('.segment');

    searchInput.addEventListener('input', (e) => {{
      const query = e.target.value.toLowerCase().trim();
      segments.forEach(seg => {{
        const text = seg.getAttribute('data-text') || '';
        if (text.includes(query)) {{
          seg.style.display = 'flex';
        }} else {{
          seg.style.display = 'none';
        }}
      }});
    }});

    function copyTranscript() {{
      const text = `{escaped_full_text}`;
      navigator.clipboard.writeText(text).then(() => {{
        alert('Transcript copied to clipboard!');
      }});
    }}
  </script>
</body>
</html>
"""


def write_rich_transcripts(job_dir: Path, title: str) -> None:
    """Generate and write transcript.md and transcript.html in the job directory."""
    transcript_txt = job_dir / "transcript.txt"
    if not transcript_txt.exists():
        return
    full_text = transcript_txt.read_text(encoding="utf-8", errors="replace")
    segments = parse_segments(job_dir)

    md_content = generate_markdown(title, segments, full_text)
    (job_dir / "transcript.md").write_text(md_content, encoding="utf-8")

    html_content = generate_html(title, segments, full_text)
    (job_dir / "transcript.html").write_text(html_content, encoding="utf-8")
