name: 💡 Feature Request
description: Suggest an idea, enhancement, or new feature for ULTRANSC
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement for ULTRANSC! Please describe your proposal below.
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a problem or limitation? Please explain.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or new feature you would like to see added.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false
